prepare:
  test_size: 0.15
  validation_size: 0.15
  random_state: 42

train:
  experiment_name: loan-default-prediction
  model_type: random_forest
  run_name: 03-rf-experiment-2
  n_estimators: 200
  max_depth: 15
  min_samples_split: 5
  random_state: 42
  class_weight: balanced

evaluate:
  threshold: 0.5